const createError = require("http-errors")
const Admin = require("../../models/about")



module.exports = async (req, res, next) => {
    try{
        console.log("fired")
        const newAdmin = Admin({
            full_name: "Adewumi David",
            mail: process.env.MAIL,
            dob: "November '96",
            password: process.env.PASSWORD,
            location: "Lagos, Nigeria", 
            job: "Software Engineer",
            bio: "Hi thereüëã, I'm David, welcome to my website. I'm a web developerü§ì, a fan of Manchester United‚ù§Ô∏è (even in this trying times ü§ß), and love video games."
        })

        const savedAdmin = await newAdmin.save()
        if(savedAdmin){
            console.log("fired: ", savedAdmin)
            const { full_name, dob, location, job, bio } = savedAdmin
            (res.status(200).json({body: {full_name, dob, location, job, bio}, message: "Admin created successfully"}))
        }
        return next(createError(501, "Internal Server Error"))

    }catch(error){
        return next(createError(500, {body: error, message: "Internal Server Error"}))
    }
}